# Generated by Django 4.2.6 on 2023-10-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Africa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('mes', models.CharField(max_length=30)),
                ('dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='America',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('mes', models.CharField(max_length=30)),
                ('dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('mes', models.CharField(max_length=30)),
                ('dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oceania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('mes', models.CharField(max_length=30)),
                ('dias', models.IntegerField()),
            ],
        ),
    ]
