# Generated by Django 4.2.6 on 2023-11-18 19:59

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_europa_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='europa',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='europa',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
