# Generated by Django 4.2.6 on 2023-11-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_europa_descripcion_europa_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='europa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='destino_img'),
        ),
    ]
